apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: devops-tools
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
