apiVersion: v1
kind: Service
metadata:
  name: hola-mundo
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: hola-mundo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
